chore: update slackbuild due to sources modification

diff --git a/plexmediaserver.SlackBuild b/plexmediaserver.SlackBuild
--- a/plexmediaserver.SlackBuild
+++ b/plexmediaserver.SlackBuild
@@ -1,10 +1,30 @@
 #!/bin/sh
-# Generated by Alien's SlackBuild Toolkit: http://slackware.com/~alien/AST
-# Copyright 2009, 2010, 2011, 2012, 2013  Eric Hameleers, Eindhoven, Netherlands
-# Slackware build script for plexmediaserver
-# Written by Lionel Young <lionelyoung@gmail.com>
-# Based on http://slackbuilds.org/template.SlackBuild
-# Fortly upgrade by Alexandre MOMPACH - 27/07/2017
+
+# Slackware build script for "plexmediaserver".
+
+# Copyright 2014-2015 Lionel Young <lionelyoung@gmail.com>
+# Copyright 2015-2017 Marcel Saegebarth <marc@mos6581.de>
+# Copyright 2017-2019 Kevin Matthew <kevin@kevinmatthew.com>
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are
+# met:
+#
+# * Redistributions of source code must retain the above copyright
+# notice, this list of conditions and the following disclaimer.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
+# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
+# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
+# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
+# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
+# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
+# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
+# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 ROOT=$(pwd)
 PRGNAM=plexmediaserver
@@ -13,20 +33,20 @@ PKG_VERSION=$(echo $VERSION | tr _ -)
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 
-if [ -z $1 ]; then
-  echo "Version is undefined. Please provide something like '1.7.6.4058-8fa494d15' without quotes as first parameter." && exit 1
-fi
-
-
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) ARCH=i486 ;;
+    i?86) ARCH=i586 ;;
     arm*) ARCH=arm ;;
        *) ARCH=$( uname -m ) ;;
   esac
 fi
 
-if [ "$ARCH" = "i486" ]; then
+CWD=$(pwd)
+TMP=${TMP:-/tmp/SBo}
+PKG=$TMP/package-$PRGNAM
+OUTPUT=${OUTPUT:-/tmp}
+
+if [ "$ARCH" = "i586" ]; then
   DEBARCH="i386"
   LIBDIRSUFFIX=""
   ARCH="i386"
@@ -43,11 +63,6 @@ else
   exit 1
 fi
 
-CWD=$(pwd)
-TMP=${TMP:-/tmp/SBo}
-PKG=$TMP/package-$PRGNAM
-OUTPUT=${OUTPUT:-/tmp}
-
 PLEX_USER=${PLEX_USER:-279}
 PLEX_GROUP=${PLEX_GROUP:-279}
 
@@ -55,8 +70,7 @@ set -e
 
 # Bail if user or group isn't valid on your system
 if ! getent passwd plex 1>/dev/null 2>/dev/null; then
-
-cat << EOF
+  cat << EOF
 
   You must have a plex user to run this script
 
@@ -65,34 +79,35 @@ cat << EOF
 
 EOF
 
-  exit
+  exit 1
 elif ! getent group plex 1>/dev/null 2>/dev/null; then
-
-cat << EOF
+  cat << EOF
 
   You must have a plex group to run this script
   # groupadd -g $PLEX_GROUP plex
 
 EOF
-  exit
+  exit 1
 fi
-
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $PKG
 rm -rf $PRGNAM-$PKG_VERSION
 ar xv $CWD/${PRGNAM}_${PKG_VERSION}_${DEBARCH}.deb
-tar xvf data.tar.gz
-# Remove debian files
-rm -f debian-binary control.tar.gz data.tar.gz
+tar xvf data.tar.?z
+rm -f debian-binary control.tar.?z data.tar.?z
 rm -rf $PKG/etc/apt/ $PKG/etc/init $PKG/etc/init.d
 chown -R root:root .
+find -L . \
+ \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
+  -o -perm 511 \) -exec chmod 755 {} \; -o \
+ \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-mkdir -p $PKG/opt/$PRGNAM/bin/ 
+mkdir -p $PKG/opt/$PRGNAM/bin/
 mv $PKG/usr/lib/plexmediaserver $PKG/opt/$PRGNAM/lib
 
-# Fix binary paths
 mv usr/sbin/start_pms $PKG/opt/$PRGNAM/bin/
 sed -i -e "s#/usr/lib/plexmediaserver#/opt/$PRGNAM/lib#" \
 	$PKG/opt/$PRGNAM/bin/start_pms
@@ -100,15 +115,14 @@ mkdir -p $PKG/usr/bin/
 ln -s /opt/$PRGNAM/bin/start_pms \
 	$PKG/usr/bin/start_pms
 
-# Install a .desktop launcher:
-mv usr/share/applications/plexmediamanager.desktop $PKG/opt/$PRGNAM/
+mv usr/share/applications/plexmediaserver.desktop $PKG/opt/$PRGNAM/
 sed -i -e "s/x-www-browser/xdg-open/" \
-	$PKG/opt/$PRGNAM/plexmediamanager.desktop
+	$PKG/opt/$PRGNAM/plexmediaserver.desktop
 mkdir -p $PKG/usr/share/applications
-ln -s /opt/$PRGNAM/plexmediamanager.desktop \
-	$PKG/usr/share/applications/plexmediamanager.desktop
+ln -s /opt/$PRGNAM/plexmediaserver.desktop \
+	$PKG/usr/share/applications/plexmediaserver.desktop
 
-rm -rf $PKG/usr/share/doc $PKG/usr/sbin $PKG/usr/lib
+rm -rf $PKG/etc/systemd $PKG/usr/share/doc $PKG/usr/sbin $PKG/usr/lib
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
@@ -120,13 +134,19 @@ mkdir -p $PKG/etc/rc.d/
 cat $CWD/rc.$PRGNAM > $PKG/etc/rc.d/rc.$PRGNAM.new
 chmod 0644 $PKG/etc/rc.d/rc.$PRGNAM.new
 
+# cleanup
+(
+  cd $PKG
+  rm -rf _gpgplex lib
+)
+
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
-# makepkg
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
+
 
 # Upgrade PLEX
 cd $ROOT && python autoUpgrade.py || echo "error during python script"
